config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'rack'
  require 'sidekiq/web'
  require 'ffaker'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  root 'home#index'

  resources :articles do
    resources :comments
    get :download_pdf
  end

  resources :categories do
    resources :subcategories
  end

  resources :users do
    patch :update_from_menu
  end
end

app/models/subcategory.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: subcategories
#
#  id          :bigint           not null, primary key
#  desc        :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :bigint           not null
#
# Indexes
#
#  index_subcategories_on_category_id  (category_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#
class Subcategory < ApplicationRecord
  has_many :articles
  belongs_to :category
end

app/controllers/subcategories_controller.rb
# frozen_string_literal: true

class SubcategoriesController < ApplicationController
  before_action :set_subcategory, only: %i[ show edit update destroy ]
  def create
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.create(params[:subcategory].permit(:name, :desc))
    redirect_to @category
  end

  def destroy
    @category = Category.find(params[:category_id])
    @subcategory = @category.subcategories.find(params[:id])
    @subcategory.destroy
    redirect_to @category
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @category = Category.find(params[:category_id])
      @subcategory = @category.subcategories.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :desc, :category_id)
    end
end

app/helpers/subcategories_helper.rb
# frozen_string_literal: true

module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<% @categories = Category.all.map{|c| [ c.name, c.id ] } %>

<%= form_with(model: @subcategory) do |f| %>
  <div class="field mb-3 mt-5">
    <%= f.label :name, class: 'form-label' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= f.label :desc, 'Desription', class: 'form-label' %>
    <%= f.text_area :desc, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= f.label :category_id, 'Parrent category', class: 'form-label' %>
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => 'Select' , class: 'form-select') %>
  </div>

  <div class="actions mb-3">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing Subcategory</h1>

<%= render 'form', subcategory: @subcategory %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', category_subcategories_path %>

app/views/subcategories/index.html.erb
<% category = Category.find(params[:category_id]) %>

<h1>Subcategories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="col">
    <% category.subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.name %></td>
        <td><%= subcategory.desc %></td>
        <td><%= category.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_category_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form', subcategory: @subcategory %>

<%= link_to 'Back', category_subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @subcategory.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @subcategory.desc %>
</p>

<p>
  <strong>Category:</strong>
  <%= @subcategory.category_id %>
</p>
<!--
<a href="<%= ('/categories/')+@subcategory.category_id.to_s+'/subcategories/'+@subcategory.id.to_s+'/edit' %>">Edit</a>
<%#= link_to 'Edit', edit_category_subcategory_path(@subcategory) %> -->
<a href="<%= ('/categories/')+@subcategory.category_id.to_s+'/subcategories/new' %>">New </a>|
<%= link_to 'Back', category_subcategories_path %>