config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'rack'
  require 'sidekiq/web'
  require 'ffaker'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  root 'home#index'

  resources :articles do
    resources :comments
    get :download_pdf
  end

  resources :categories do
    resources :subcategories
  end

  resources :users do
    patch :update_from_menu
  end
end

app/models/article.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: articles
#
#  id          :bigint           not null, primary key
#  body        :text
#  title       :string
#  visit_count :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :string
#
class Article < ApplicationRecord
  validates :title, :presence => true,
            :length => { :minimum => 5 }

  has_many :comments, :dependent => :destroy
  belongs_to :category
  has_one_attached :cover_picture

  def self.ransckable_attributes(auth_object = nil)
    ["title", "published_at"]
  end
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @q = Article.ransack(params[:q])
    @pagy, @articles = pagy(@q.result, items: 1)
  end

  # GET /articles/1 or /articles/1.json
  def show
    result = Articles::Show.call(user: current_user, article: @article, request: request)
    if result.successful?
      @article = Article.find(params[:id])
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @article }
      end
    else
      render partial: 'templates/404'
    end
  end

  def download_pdf
    filename = '404_pdf'
    page_404 = ApplicationController.new.render_to_string( partial: '/templates/404')
    pdf = Grover.new(page_404, format: 'A5', layout: 'pdf').to_pdf
    send_data pdf, filename: filename, type: 'application/pdf'
    Article.broadcast_notification({ title: current_user.name, message: 'Has downloaded the PDF' })
  end

  # GET /articles/new
  def new
    @article = Article.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /articles/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.category_id = params[:category_id]
    @categories = Category.all.map{|c| [ c.name, c.id ] }
    #Article.broadcast_notification({ title: current_user.role, message: 'Has created new article' })

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    @article.category_id = params[:category_id]

    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    Article.broadcast_notification({ title: current_user.name, message: 'Has removed article!' })
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body, :cover_picture)
    end
end

app/helpers/articles_helper.rb
# frozen_string_literal: true

module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field mb-3 mt-5">
    <%= form.label :cover_picture, class: 'form-label' %>
    <%= form.file_field :cover_picture, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label :title, class: 'form-label' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label :body, class: 'form-label' %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select", class: 'form-select') %>
  </div>

  <div class="actions mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h2>Search</h2>

<%= search_form_for @q do |f| %>
  <div class="row g-3">
    <div class="col-auto">
      <%= f.search_field :title_cont, class: 'form-control', placeholder: "Search by" %>
    </div>
    <div class="col-auto">
      <%= f.submit name: '', class: 'btn btn-primary'%>
    </div>
    <div class="col-auto">
      <%= link_to "Clear", request.path, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>
<br>
<br>

<h1>Articles</h1>
<table class="table article_list">
  <thead>
  <tr class="g-5">
    <th class="col-md-1"><%= sort_link @q, :id, "#ID" %></th>
    <th class="col-md-1"><%= sort_link @q, :created_at, "Date", default_order: :desc %></th>
    <th class="col-md-2"><%= sort_link @q, :title, "Title", default_order: :desc %></th>
    <th class="col-md-3"><%= sort_link @q, :body, "Body", default_order: :desc %></th>
    <th class="col-md-2">Comments</th>
    <td class="col-md-1"></td>
    <td class="col-md-1"></td>
    <td class="col-md-1"></td>
  </tr>
  </thead>
  <tbody>
  <% @articles.each do |article| %>
    <tr class="g-5">
      <td class="col-md-1"><%= article.id %></td>
      <td class="col-md-1"><%= article.created_at.strftime("%d.%m.%Y") %></td>
      <td class="col-md-2"><%= article.title %></td>
      <td class="col-md-3"><%= article.body %></td>
      <td class="col-md-2"><%= article.comments.count %></td>
      <td class="col-md-1"><%= link_to 'Show', article, class: "btn btn-primary" %></td>
      <td class="col-md-1"><%= link_to 'Edit', edit_article_path(article), class: "btn btn-primary"  %></td>
      <td class="col-md-1"><%= link_to 'Destroy', article, method: :delete, class: "btn btn-primary" , data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= render partial: 'templates/article-pagination' %>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% article = @article %>
<p>
  <strong>Download PDF:</strong>
  <%= link_to '404 Page', article_download_pdf_path(article.id), :target => '_blank' %>
</p>
</br>
<h6>Number of views: <%= article.visit_count %></h6>
<p>
  <strong>Published:</strong>
  <%= article.created_at.strftime("%d.%m.%Y") %>
</p>
<p>
  <strong>Cover picture:</strong>
</p>
<% if article.cover_picture %>
  <p class="cover_picture">
    <%= image_tag(article.cover_picture) %>
  </p>
<% end %>

<p>
  <strong>Title:</strong>
  <%= article.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= article.body %>
</p>

<p>
  <strong>Category:</strong>
  <% category = Category.find(article.category_id) %>
  <%= category.name %>
</p>
</br>
</br>

<h5><b>COMMENTS ( <%= article.comments.count %> )</b></h5>
<% article.comments.each do |comment| %>

  <p class="pt-3">
    <b>Author:</b>
    <%= comment.author %>
  </p>

  <p>
    <b>Date:</b>
    <%= comment.created_at.strftime("%d.%m.%Y") %>
  </p>

  <p>
    <b>Comment:</b>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to 'Destroy Comment', [comment.article, comment],
      :confirm => 'Are you sure?',
      :method => :delete
    %>
  </p>
<% end %>

<div class="card">
  <div class="card-body">
    <p class="font-weight-bold">Add a comment:</p>
    <%= form_with(model: [article, article.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.label :author %><br />
        <%= f.text_field :author, class: 'form-control', value:current_user.name  %><br />
        <%= f.label :body %><br />
        <%= f.text_area :body, class: 'form-control' %><br />
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>
<br />
<%= link_to 'Edit', edit_article_path(article) %> |
<%= link_to 'Back', articles_path %>