config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'rack'
  require 'sidekiq/web'
  require 'ffaker'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  root 'home#index'

  resources :articles do
    resources :comments
    get :download_pdf
  end

  resources :categories do
    resources :subcategories
  end

  resources :users do
    patch :update_from_menu
  end
end

app/views/templates/_article-pagination.html.erb
<% link = pagy_link_proc(@pagy, 'class="page-link"') -%>
<nav aria-label="pager"  class="pagy-bootstrap-nav" role="navigation">
  <ul class="pagination">
    <% if @pagy.prev -%>
      <li class="page-item prev"><%== link.call(@pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></li>
    <% else -%>
      <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %></a></li>
    <% end -%>
    <% @pagy.series.each do |item| -%>
      <% if item.is_a?(Integer) -%>
        <li class="page-item"><%== link.call(item) %></li>
      <%   elsif item.is_a?(String)  -%>
        <li class="page-item active"><%== link.call(item) %></li>
      <% elsif item == :gap -%>
        <li class="page-item disabled gap"><a href="#" class="page-link"><%== pagy_t('pagy.nav.gap') %></a></li>
      <% end -%>
    <% end -%>
    <% if @pagy.next -%>
      <li class="page-item next"><%== link.call(@pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></li>
    <% else -%>
      <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
    <% end -%>
  </ul>
</nav>

app/views/templates/_footer.html.erb
<nav class="footer navbar navbar-expand-lg w-100">
  <a class="navbar-brand" href="/">Sports Hub</a>

  <div class="container d-block">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="footer-pills">
      <li>Copyright 2019 Sports Hub</li></br>
      <li>Privacy / Terms</li>
    </ul>
  </div>
</nav>

app/views/templates/_main_nav.html.erb
<% user = current_user %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script>
    $(document).ready(function() {
        $('#user_locale').on('change', function () {
            $('.UpdateLocale').trigger('click');
        })
    });
</script>

<nav class="header navbar navbar-expand-lg navbar-light bg-light p-0">
  <a class="navbar-brand" href="/"><%= t('Sports Hub') %></a>
  <div class="container">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
        <input type="search" class="form-control" placeholder="Search by" aria-label="Search">
      </form>
    </div>
    <% if user_signed_in? %>
      <div class="d-block position-relative">
        <a href="#" class="d-block position-relative link-dark text-decoration-none p-0" id="dropdownUser2" data-bs-toggle="dropdown" aria-expanded="false">
          <div class="d-flex align-items-center dropdown-toggle">
            <div class="col-3 bg-light p-3">
              <% if (user.user_picture.attach(params[:user_picture]) == true ) -%>
                <img src="https://agile.yakubovsky.com/wp-content/plugins/all-in-one-seo-pack/images/default-user-image.png" class="rounded-circle avatar"/>
              <% end -%>
              <% if user.user_picture -%>
                <!--    <%#= image_tag user.user_picture, class:"rounded-circle avatar" %>-->
              <% end -%>
            </div>
            <div class="col-7 bg-light p-3">
              <strong><%= current_user.name %></strong></br>
              <%= current_user.role %>
            </div>
          </div>
        </a>
        <ul class="dropdown-menu text-small shadow m-0 p-0 profile-drop-menu" aria-labelledby="dropdownUser2" style="">
          <li><%= link_to "View profile", user_path(current_user), :class => 'dropdown-item' %></li>
          <li><%= link_to "Change password", edit_user_registration_path+'#pills-password', :class => 'dropdown-item' %></li>
          <li><%= link_to "My Surveys", user_path(current_user), :class => 'dropdown-item' %></li>
          <li><%= link_to "Team hub", user_path(current_user), :class => 'dropdown-item' %></li>
          <li>
            <hr class="dropdown-divider m-0">
          </li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'dropdown-item' %></li>
        </ul>
        </div>
      <div class="nav-item d-block position-relative">
        <%= form_with(model: current_user, url: user_update_from_menu_path(current_user.id)) do |f| %>
            <%= f.select(:locale, {'EN' => :en,'UA' => :ua,'NL' => :nl}, {}, { :class => 'form-control form-select' }) %>
          <%= f.submit "Update".html_safe, class: 'UpdateLocale'%>
        <% end %>
      </div>
      <% else %>
      <div class="row align-items-center text-white">
        <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link red col'  %>
        <%= link_to "Login in", new_user_session_path, :class => 'navbar-link btn btn-outline-danger login-btn col'  %>
        <div class="col nav-item dropdown d-flex align-items-center justify-content-center">
            <a class="nav-link dropdown-toggle form-control form-select" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">EN</a>
            <ul class="dropdown-menu text-small shadow lang-drop-menu" aria-labelledby="dropdownUser2" style="">
              <li><a class="dropdown-item" href="#">UA</a></li>
              <hr class="dropdown-divider">
              <li><a class="dropdown-item" href="#">NL</a></li>
            </ul>
        </div>
      </div>
    <% end %>
  </div>
</nav>

app/views/templates/_notices.html.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<%= render partial: 'shared/notification' %>

app/views/templates/_sidebar_left.html.erb
<% @categories = Category.all %>

<div data-component="sidebar">
  <div class="sidebar">
    <ul class="list-group flex-column d-inline-block first-menu">
        <li class="list-group-item pl-3 py-2">
        <a href="/" class="">
          <i class="fa fa-user-o" aria-hidden="true">
            <span class="ml-2 align-middle">Home</span>
          </i>
        </a>
      </li>
      <% @categories.includes(:subcategories).each do |category| %>
        <li class="list-group-item pl-3 py-2">
          <i>
            <!--<span class="ml-2 align-middle"><%#= link_to category.name, category_path(category), remote: true %></span>-->
            <span class="ml-2 align-middle"><%= link_to category.name, category_path(category) %></span>
            <ul class="list-group flex-column d-inline-block submenu">
              <% category.subcategories.each do |subcategory| %>
                <li class="list-group-item pl-4">
                  <%= link_to subcategory.name, ('/categories/')+subcategory.category_id.to_s+'/subcategories/'+subcategory.id.to_s %>
                </li>
              <% end %>
            </ul>
          </i>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/templates/_sidebar_right.html.erb
<% @articles = Article.all %>

<div data-component="sidebar">
  <div class="sidebar">
    <ul class="list-group flex-column d-inline-block first-menu">
      <li class="list-group-item pl-3 py-2">
        <a href="#"><%= t('hello') %></a>
      </li>
      <li class="list-group-item pl-3 py-2">
        <%= link_to 'Categories', categories_path %>
      </li>
    </ul>
  </div>
</div>