config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'rack'
  require 'sidekiq/web'
  require 'ffaker'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  root 'home#index'

  resources :articles do
    resources :comments
    get :download_pdf
  end

  resources :categories do
    resources :subcategories
  end

  resources :users do
    patch :update_from_menu
  end
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id         :bigint           not null, primary key
#  desc       :text
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Category < ApplicationRecord
  has_many :articles
  has_many :subcategories, :dependent => :destroy
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @presenter = CategoriesArticleShowPresenter.new
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :desc)
    end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3 mt-5">
    <%= form.label :name, class: 'form-label' %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="field mb-3">
    <%= form.label :desc, class: 'form-label' %>
    <%= form.text_area :desc, class: 'form-control' %>
  </div>

  <div class="actions mb-3">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<table class="table article_list">
  <thead>
  <tr>
    <th scope="col">#ID</th>
    <th scope="col">Date</th>
    <th scope="col">Name</th>
    <th scope="col">Articles</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @presenter.categories.each do |category| %>
    <tr>
      <td><%= category.id %></td>
      <td><%= @presenter.date_category_format(category) %></td>
      <td><%= category.name %></td>


        <td><%= @presenter.category_count(category) %></td>

      <td><%= link_to 'Show', category %></td>
      <td><%= link_to 'Edit', edit_category_path(category) %></td>
      <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% category = @category %>
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @category.desc %>
</p>

<h5 class="mt-5 mb-3"><b>SUBCATEGORIES ( <%= category.subcategories.count %> )</b></h5>
<% category.subcategories.each do |subcategory| %>
  <p>
    <b>Name:</b>
    <a href="<%= ('/categories/')+category.id.to_s+'/subcategories/'+subcategory.id.to_s %>"><%= subcategory.name %></a>
    <b>Date:</b>
    <%= subcategory.created_at.strftime("%d.%m.%Y") %>
    <b>Description:</b>
    <%= subcategory.desc %>
  </p>

  <p class="mb-5">
    <%= link_to 'Destroy Subcategory', [subcategory.category, subcategory],
                :confirm => 'Are you sure?',
                :method => :delete
    %>
  </p>
<% end %>

<% @article = Article.find_by category_id: @category.id %>
<% if @article %>
  <h5 class="mt-5 mb-3"><b>ARTICLES:</b></h5>
  <p>
    <b>Title:</b>
    <%= link_to @article.title, article_path(@article) %>
    <b>Date:</b>
    <%= @article.created_at.strftime("%d.%m.%Y") %>
    <b>Description:</b>
    <%= @article.body %>
  </p>
<% end %>


<div class="card mt-5 mb-3">
  <div class="card-body">
    <p class="font-weight-bold">Add subcategory:</p>
    <%= form_with(model: [category, category.subcategories.build]) do |f| %>
      <div class="form-group">
        <%= f.label :name %><br />
        <%= f.text_field :name, class: 'form-control' %><br />
        <%= f.label :desc %><br />
        <%= f.text_area :desc, class: 'form-control' %><br />
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/show.js.erb
categories = '<%= raw @category.subcategories.all.map{|c| '<li class="list-group-item pl-4">' + c.name + '</li>' }.join %>'
console.log(categories);

$('.submenu').html(categories);